config/routes.rb
Swagpg::Application.routes.draw do
  
  resources :trades

  root :to => "pages#home"
  
  match "auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/auth/twitter" => "sessions#new", :as => :signintwitter
  match "/auth/github" => "sessions#new", :as => :signingithub
  match "/dashboard" => "pages#dashboard"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  
  attr_accessible :designer, :developer, :image, :others, :title, :image_cache, :desc
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  
  has_many :trades
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_filter :authenticate, :except => :home

  def authenticate
    redirect_to :root unless session[:user_id]
  end
  
  def home
    @users = User.all
    @trades = Trade.order('created_at DESC')
  end
  
  def dashboard
    @trades = current_user.trades.order('created_at DESC').paginate(:per_page => 5, :page => params[:page])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to dashboard_path, :notice => "Signed In"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed Out"
  end
  
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  before_filter :authenticate 

  def authenticate
    redirect_to :root unless session[:user_id]
  end

  def index
    @trades = Trade.order('created_at DESC').paginate(:per_page => 5, :page => params[:page])
    @user = User.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
    end
  end

  #Trade.find(params[:id])
  
  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = current_user.trades.build(params[:trade])
    
    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swagpg</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="nav">
		<% if current_user %>
			<%= link_to "#{current_user.name} dashboard", dashboard_path %>&nbsp;
			<%= link_to "Sign Out", signout_path %>.
		<% else %>
			<%= link_to "Sign in with Twitter", signintwitter_path, :class => "btn-auth btn-twitter" %>
			
		<% end %>
</div>
<div class="grater-container content">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="grater" style="margin-top:20px;">
	<h1><span style="background:#000;"><%= link_to '+ new trade', new_trade_path, :class => "addnew" %></span>&nbsp;<span style="background:#000;"><%= link_to 'Trade feed', trades_path, :class => "addnew" %></span><%= image_tag(current_user.image.to_s, :class => "dimm img-circle", :style => "float:right;") %></h1>
</div>
<div class="grater">
	<div>
		<h3>Your Posted Trades: <%= current_user.trades.count %></h3>
	</div>
</div>
<div class="grater">
	<% @trades.each do |trade| %>
	  <p class="title"><%= link_to trade.title, trade, :class => "title" %></p>
	  <p><%= image_tag(trade.image_url, :class => "feed-images") if trade.image? %></p>
	  <p>  
	 	<% if trade.developer? %>
		<a class="developers" href="#"><span style="background:#fea700;padding:3px;">Developers</span></a>
		<% end %>
	    <% if trade.designer? %>
		<a class="designers" href="#"><span style="background:#399dd8;padding:3px;">Designers</span></a>
		<% end %>
	    <% if trade.others? %>
		<a class="other" href="#"><span style="background:#f2217c;padding:3px;">Other</span></a>
		<% end %>
	  </p>
	  <h6>Created <%= time_ago_in_words(trade.created_at) %> ago by <%= link_to trade.user_name, trade %></h6>
	<% end %>
</div>
<div class="grater">
	<%= will_paginate @trades %>
</div>

app/views/pages/home.html.erb
<div class="grater">
	<h2><span style="background:#000;color:#fff;padding:5px;">mt. swag</span></h2>
	<h5><span style="background:#000;color:#fff;padding:5px;">Elevation: <%= @users.count %> m (<%= sprintf("%.1f",@users.count * 2.2) %> ft)</span></h5>
</div>
<div class="grater">
	<div>
		<h3>What is Mt. Swag?</h3>
		<p>startups, developers and designers love just one thing, more than beta invites...</p>
		<%= image_tag('P1020415.jpeg', :class=> "img-circle dimm")%>
		<p>Mt. Swag is a simple network to trade your startup (or company) swag with those who love your brand, idea, team, design, or whatever the reason is.</p>
	</div>
	<div>
		<h3>Current Climbers</h3>
	<% @users.each do |user| %>
		<img src="<%= user.image %>" class="dimm" />
	<% end %>
	</div>
</div>
<div class="grater">
	<h3>Whats being traded?</h3>
	<% @trades.each do |trade| %>
		<%= image_tag(trade.image_url, :class => "home-images") if trade.image? %>
	<% end %>
</div>

app/views/trades/_form.html.erb
<div class="grater">
	<div>
	<%= simple_form_for @trade do |f| %>
		<%= f.error_notification %>
		<h3>S'plain it..</h3>
		<%= f.input :title, :label => "What are you Trading?" %>
		<%= f.input :desc, :label => "Explain what you want to accomplish" %>
	</div>
	<div>
		<h3>Who will like this trade best?</h3>
		<p><%= f.input :designer %></p>
		<p><%= f.input :developer %></p>	
		<p><%= f.input :others %></p>
		<hr />
		<h3>Upload a Picture</h3>
		<p><%= f.input :image, :label => "Choose Image", :style => "padding:5px" %></p>
		<hr />
		<h3>Create this monkay</h3>
		<p><%= f.button :submit, :class => "title" %></p>
	<% end %>
	</div>
</div>	

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<div class="grater" style="margin-top:20px;">
	<h1><span style="background:#000;"><%= link_to '+ new trade', new_trade_path, :class => "addnew" %></span>&nbsp;<span style="background:#000;"><%= link_to 'Dashboard', dashboard_path, :class => "addnew" %></span><%= image_tag(current_user.image.to_s, :class => "dimm img-circle", :style => "float:right;") %></h1>
</div>
<div class="grater">
<% @trades.each do |trade| %>
  <p class="title"><%= link_to trade.title, trade, :class => "title" %></p>
  <p><span class="bodytext"><%= trade.desc %></span></p>
  <p><%= image_tag(trade.image_url, :class => "feed-images") if trade.image? %></p>
  <p>  
 	<% if trade.developer? %>
	<a class="developers" href="#"><span style="background:#fea700;padding:3px;">Developers</span></a>
	<% end %>
    <% if trade.designer? %>
	<a class="designers" href="#"><span style="background:#399dd8;padding:3px;">Designers</span></a>
	<% end %>
    <% if trade.others? %>
	<a class="other" href="#"><span style="background:#f2217c;padding:3px;">Other</span></a>

	<% end %>
  </p>
  <h6>Created <%= time_ago_in_words(trade.created_at) %> ago by <%= link_to trade.user_id, trade %></h6>

<% end %>
</div>
<div class="grater">
	<%= will_paginate @trades %>
</div>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<h1><span style="background:#000;"><%= link_to '<- Feed', trades_path, :class => "addnew" %></span><%= image_tag(current_user.image.to_s, :class => "dimm img-circle", :style => "float:right;") %></h1>

<p class="title"><%= @trade.title %></p>
  <p><%= image_tag(@trade.image_url, :class => "feed-images") if @trade.image? %></p>
  <p>  
 	<% if @trade.developer? %>
	<a class="developers" href="#"><span style="background:#fea700;padding:3px;">Developers</span></a>
	<% end %>
    <% if @trade.designer? %>
	<a class="designers" href="#"><span style="background:#399dd8;padding:3px;">Designers</span></a>
	<% end %>
    <% if @trade.others? %>
	<a class="other" href="#"><span style="background:#f2217c;padding:3px;">Other</span></a>
	<% end %>
  </p>
  <h6>Created <%= time_ago_in_words(@trade.created_at) %> ago</h6>
    <%= link_to 'Show', @trade %>&nbsp;<%= link_to 'Edit', edit_trade_path(@trade) %>&nbsp;<%= link_to 'Destroy', @trade, method: :delete, data: { confirm: 'Are you sure?' } %>